//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


//INSTANT C# NOTE: Formerly VB project-level imports:
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System;

namespace SuperiorPackGroup
{
	namespace Properties
	{

		//This class was auto-generated by the StronglyTypedResourceBuilder
		//class via a tool like ResGen or Visual Studio.
		//To add or remove a member, edit your .ResX file then rerun ResGen
		//with the /str option, or rebuild your VS project.
		///<summary>
		///  A strongly-typed resource class, for looking up localized strings, etc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal static class Resources
		{

			private static global::System.Resources.ResourceManager resourceMan;

			private static global::System.Globalization.CultureInfo resourceCulture;

			///<summary>
			///  Returns the cached ResourceManager instance used by this class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperiorPackGroup.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			///<summary>
			///  Overrides the current thread's CurrentUICulture property for all
			///  resource lookups using this strongly typed resource class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap address_book2_24
			{
				get
				{
					object obj = ResourceManager.GetObject("address_book2_24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap address_book2_32
			{
				get
				{
					object obj = ResourceManager.GetObject("address_book2_32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap box_closed24
			{
				get
				{
					object obj = ResourceManager.GetObject("box_closed24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap box_closed32
			{
				get
				{
					object obj = ResourceManager.GetObject("box_closed32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Inventory24
			{
				get
				{
					object obj = ResourceManager.GetObject("Inventory24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Inventory32
			{
				get
				{
					object obj = ResourceManager.GetObject("Inventory32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap InventoryAdjustment24
			{
				get
				{
					object obj = ResourceManager.GetObject("InventoryAdjustment24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap InventoryAdjustment32
			{
				get
				{
					object obj = ResourceManager.GetObject("InventoryAdjustment32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap ItemPool_24
			{
				get
				{
					object obj = ResourceManager.GetObject("ItemPool_24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap ItemPool_32
			{
				get
				{
					object obj = ResourceManager.GetObject("ItemPool_32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
			///</summary>
			internal static System.Drawing.Icon logolg
			{
				get
				{
					object obj = ResourceManager.GetObject("logolg", resourceCulture);
					return (System.Drawing.Icon)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewCustomer16
			{
				get
				{
					object obj = ResourceManager.GetObject("NewCustomer16", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewCustomer32
			{
				get
				{
					object obj = ResourceManager.GetObject("NewCustomer32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewInventoryAdjustment24
			{
				get
				{
					object obj = ResourceManager.GetObject("NewInventoryAdjustment24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewInventoryAdjustment32
			{
				get
				{
					object obj = ResourceManager.GetObject("NewInventoryAdjustment32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewInventoryBuildAssembly24
			{
				get
				{
					object obj = ResourceManager.GetObject("NewInventoryBuildAssembly24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap NewInventoryBuildAssembly32
			{
				get
				{
					object obj = ResourceManager.GetObject("NewInventoryBuildAssembly32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Project24
			{
				get
				{
					object obj = ResourceManager.GetObject("Project24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Project32
			{
				get
				{
					object obj = ResourceManager.GetObject("Project32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Schedule24
			{
				get
				{
					object obj = ResourceManager.GetObject("Schedule24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Schedule32
			{
				get
				{
					object obj = ResourceManager.GetObject("Schedule32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Ship24
			{
				get
				{
					object obj = ResourceManager.GetObject("Ship24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap Ship32
			{
				get
				{
					object obj = ResourceManager.GetObject("Ship32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap UpdateInventoryWarehouse24
			{
				get
				{
					object obj = ResourceManager.GetObject("UpdateInventoryWarehouse24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap UpdateInventoryWarehouse32
			{
				get
				{
					object obj = ResourceManager.GetObject("UpdateInventoryWarehouse32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap WarehouseLocation_24
			{
				get
				{
					object obj = ResourceManager.GetObject("WarehouseLocation_24", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap WarehouseLocation_32
			{
				get
				{
					object obj = ResourceManager.GetObject("WarehouseLocation_32", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}
		}
	}

}