<?xml version="1.0" encoding="utf-8"?><Database Name="SPGData" Class="SPGDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SPGData;Integrated Security=True" SettingsObjectName="DXDAL.My.MySettings" SettingsPropertyName="SPGDataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblInventory" Member="tblInventories">
    <Type Name="tblInventory">
      <Column Name="InventoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InventoryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InventoryItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InventoryQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InventoryPallets" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="strEnteredBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dtmEnteredOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="PO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lot" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Shift" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pallet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblItem_tblInventory" Member="tblItem" ThisKey="InventoryItemID" OtherKey="ItemID" Type="tblItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblItems" Member="tblItems">
    <Type Name="tblItem">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemCustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemDefaultMachine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemProdStandard" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ItemPicture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="dblPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="sngRebate" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="strUnitOfMeasure" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="intQtyPerUnit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strEnteredBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dtmEnteredOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dblFreight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblFilm" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblBoxes" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblStretchWrap" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblPallets" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblOther1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblOther2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblOther3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblOther4" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dblOther5" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="intUnitsPerCase" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="intUnitsPerPallet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intCasesPerPallet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sngQuantityOnHand" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="CaseGrossWeight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PackageCode" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="CaseCode" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="RequiredWeight" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MAV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CasesPerLayer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LayersPerPallet" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShelfLife" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Instructions" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="PalletPattern" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Editing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Packers" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UPC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblItem_tblInventory" Member="tblInventories" ThisKey="ItemID" OtherKey="InventoryItemID" Type="tblInventory" />
      <Association Name="tblItem_tblBOM" Member="tblBOMs" ThisKey="ItemID" OtherKey="BOMFiniGoodID" Type="tblBOM" />
      <Association Name="tblItem_tblBOM1" Member="tblBOMs1" ThisKey="ItemID" OtherKey="BOMRawMatID" Type="tblBOM" />
      <Association Name="tblItem_LocationInventory" Member="LocationInventories" ThisKey="ItemID" OtherKey="LocationInvenoryItem" Type="LocationInventory" />
    </Type>
  </Table>
  <Table Name="dbo.tblBOMs" Member="tblBOMs">
    <Type Name="tblBOM">
      <Column Name="BOMID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BOMRawMatID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BOMFiniGoodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BOMQuantity" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ts" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="ScrapFactor" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsPool" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblItem_tblBOM" Member="tblItem" ThisKey="BOMFiniGoodID" OtherKey="ItemID" Type="tblItem" IsForeignKey="true" />
      <Association Name="tblItem_tblBOM1" Member="tblItem1" ThisKey="BOMRawMatID" OtherKey="ItemID" Type="tblItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LocationInventory" Member="LocationInventories">
    <Type Name="LocationInventory">
      <Column Name="OID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Location" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocationInvenoryItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantityOnHand" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OptimisticLockField" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCRecord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblItem_LocationInventory" Member="tblItem" ThisKey="LocationInvenoryItem" OtherKey="ItemID" Type="tblItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>